SIM=icarus
TOPLEVEL_LANG=verilog
VERILOG_SOURCES=$(shell pwd)/two_bit_comparator.v
TOPLEVEL=two_bit_comparator
MODULE=test_two_bit_comparator

WAVES=1
include $(shell cocotb-config --makefiles)/Makefile.sim

