SIM=icarus

TOPLEVEL_LANG=verilog

MODULE=test_up_counter_4bit

TOPLEVEL=up_counter_4bit

VERILOG_SOURCES=$(shell pwd)/up_counter_4bit.v

WAVES=1


include $(shell cocotb-config --makefiles)/Makefile.sim


