SIM=icarus

TOPLEVEL_LANG=verilog

TOPLEVEL=sipo_shift_register

VERILOG_SOURCES=$(shell pwd)/sipo_shift_register.v

MODULE=test_sipo_shift_register

WAVES=1

include $(shell cocotb-config --makefiles)/Makefile.sim

