VERILOG_SOURCES = $(PWD)/up_counter_4bit_jkff.v
TOPLEVEL = up_counter_4bit_jkff
MODULE = test_up_counter_4bit_jkff
TOPLEVEL_LANG = verilog
SIM = icarus

WAVES=1
include $(shell cocotb-config --makefiles)/Makefile.sim

